.PHONY: all build contract data-driver clean tree

all: build

build: contract data-driver

# Build the contract WASM (default features = contract)
contract:
	@cargo build -p my-first-contract --release --target wasm32-unknown-unknown
	@mkdir -p target/stripped
	@cp target/wasm32-unknown-unknown/release/my_first_contract.wasm target/stripped/counter_contract.wasm
	@echo "Contract WASM: target/stripped/counter_contract.wasm"

# Build the data-driver WASM (generated by #[contract] macro)
data-driver:
	@cargo build -p my-first-contract --release --target wasm32-unknown-unknown --no-default-features --features data-driver
	@mkdir -p target/stripped
	@cp target/wasm32-unknown-unknown/release/my_first_contract.wasm target/stripped/counter_data_driver.wasm
	@echo "Data-driver WASM: target/stripped/counter_data_driver.wasm"

clean:
	@cargo clean

tree:
	@echo "Artifacts:" && \
	ls -1 target/stripped/*.wasm 2>/dev/null || true
