[package]
name = "my-first-contract"
version = "0.1.0"
edition = "2021"
description = "A simple example smart contract written for the Dusk smart contract platform and used in the docs as an illustration"
readme = "README.md"
license = "MPL-2.0"
repository = "https://github.com/dusk-network/my-first-contract"
keywords = ["dusk", "smart contract"]
categories = ["wasm", "cryptography::cryptocurrencies"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["contract"]
contract = ["dusk-core/abi-dlmalloc"]
data-driver = ["dep:dusk-data-driver", "dusk-data-driver/wasm-export", "dusk-data-driver/alloc", "dusk-core/serde"]

[dependencies]
dusk-core = { git = "https://github.com/dusk-network/rusk/", branch = "master" }
dusk-forge = "0.2"
dusk-data-driver = { git = "https://github.com/dusk-network/rusk", branch = "master", optional = true }
